
package view;
import java.awt.Color;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.table.DefaultTableModel;
import java.util.List;
import java.time.LocalDate;
import javax.swing.JMenuItem;
import javax.swing.JOptionPane;
import model.Piloto;
import model.PilotoDAO;
/**
 *
 * @author Camilo Jurado
 */
public class Administrador extends javax.swing.JFrame {

    /**
     * Creates new form Administrador
     */
    public Administrador() {
        initComponents();
        this.setLocationRelativeTo(null);
        cargarPilotosEnTabla();
        iniciarOpciones();
    }
     public void cargarPilotosEnTabla() {
        PilotoDAO pilotoDAO = new PilotoDAO();
        List<Piloto> listaPilotos = pilotoDAO.obtenerPiloto();

        DefaultTableModel model = (DefaultTableModel) Tablepiloto.getModel();
        model.setRowCount(0); 

        for (Piloto piloto : listaPilotos) {
            model.addRow(new Object[]{
                piloto.getCodigo(),
                piloto.getNombre(),
                piloto.getApellido(),
                piloto.getCorreo(),
                piloto.getTelefono(),
                piloto.getavion()
            });
        }
    }
}
    public void iniciarOpciones() {
        JMenuItem open = new JMenuItem("Mas Info");
        JMenuItem editar = new JMenuItem("Editar");
        JMenuItem eliminar = new JMenuItem("Despedir");
        
        ppMenuTabla.add(open);
        ppMenuTabla.add(editar);
        ppMenuTabla.add(eliminar);

        jTablePilotos.setComponentPopupMenu(ppMenuTabla);

       
        eliminar.addActionListener(new ActionListener() {
            @Override

            public void actionPerformed(ActionEvent e) {
                int selectedRow = tablePilotos.getSelectedRow();

                if (selectedRow != -1) { 
                    
                    String codigoPiloto = (String) jTablepiloto.getValueAt(selectedRow, 0);

                    
                    int confirm = JOptionPane.showConfirmDialog(null, "seguro de que deseas eliminar al piloto?", "Confirmación", JOptionPane.YES_NO_OPTION);
                    if (confirm == JOptionPane.YES_OPTION) {
                       
                        PilotoDAO pilotoDAO = new PilotoDAO();
                        pilotoDAO.eliminarPiloto(codigoPiloto);

                    }
                } else {
                    JOptionPane.showMessageDialog(null, "Seleccione un profesor para eliminar.");
                

            }
        });
    }

    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ppMenuTabla = new javax.swing.JPopupMenu();
        open = new javax.swing.JMenuItem();
        editar = new javax.swing.JMenuItem();
        eliminar = new javax.swing.JMenuItem();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jPanel9 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jPanel10 = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel6 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        Tablepiloto = new javax.swing.JTable();
        jButton3 = new javax.swing.JButton();
        jPanel11 = new javax.swing.JPanel();
        jLabel23 = new javax.swing.JLabel();
        jTextField5 = new javax.swing.JTextField();
        jSeparator8 = new javax.swing.JSeparator();
        jLabel24 = new javax.swing.JLabel();
        jTextField8 = new javax.swing.JTextField();
        jSeparator9 = new javax.swing.JSeparator();
        jLabel25 = new javax.swing.JLabel();
        jTextField9 = new javax.swing.JTextField();
        jSeparator10 = new javax.swing.JSeparator();
        jLabel26 = new javax.swing.JLabel();
        jTextField10 = new javax.swing.JTextField();
        jSeparator11 = new javax.swing.JSeparator();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jSeparator12 = new javax.swing.JSeparator();
        jLabel31 = new javax.swing.JLabel();
        jComboBox3 = new javax.swing.JComboBox<>();
        jLabel32 = new javax.swing.JLabel();
        jSeparator14 = new javax.swing.JSeparator();
        jComboBox4 = new javax.swing.JComboBox<>();
        jSeparator13 = new javax.swing.JSeparator();
        jButton2 = new javax.swing.JButton();
        jPanel25 = new javax.swing.JPanel();
        jLabel55 = new javax.swing.JLabel();
        jLabel56 = new javax.swing.JLabel();
        jLabel57 = new javax.swing.JLabel();
        jSeparator7 = new javax.swing.JSeparator();
        jLabel58 = new javax.swing.JLabel();
        jLabel59 = new javax.swing.JLabel();
        jLabel60 = new javax.swing.JLabel();
        jProgressBar7 = new javax.swing.JProgressBar();
        jLabel61 = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        jSeparator15 = new javax.swing.JSeparator();
        btnContratar = new javax.swing.JButton();
        jLabel62 = new javax.swing.JLabel();
        txtApellidos = new javax.swing.JTextField();
        jSeparator16 = new javax.swing.JSeparator();
        jLabel64 = new javax.swing.JLabel();
        txtCorreo = new javax.swing.JTextField();
        jSeparator17 = new javax.swing.JSeparator();
        jSeparator19 = new javax.swing.JSeparator();
        jPanel26 = new javax.swing.JPanel();
        jLabel63 = new javax.swing.JLabel();
        jLabel67 = new javax.swing.JLabel();
        jLabel68 = new javax.swing.JLabel();
        jSeparator20 = new javax.swing.JSeparator();
        jLabel69 = new javax.swing.JLabel();
        jLabel70 = new javax.swing.JLabel();
        jLabel71 = new javax.swing.JLabel();
        jProgressBar8 = new javax.swing.JProgressBar();
        jLabel72 = new javax.swing.JLabel();
        txtNombre1 = new javax.swing.JTextField();
        jSeparator21 = new javax.swing.JSeparator();
        btnContratar1 = new javax.swing.JButton();
        jLabel73 = new javax.swing.JLabel();
        txtApellidos1 = new javax.swing.JTextField();
        jSeparator22 = new javax.swing.JSeparator();
        jLabel74 = new javax.swing.JLabel();
        txtCorreo1 = new javax.swing.JTextField();
        jSeparator23 = new javax.swing.JSeparator();
        jLabel75 = new javax.swing.JLabel();
        txtTelefono = new javax.swing.JTextField();
        txtTelefono1 = new javax.swing.JTextField();
        jSeparator24 = new javax.swing.JSeparator();
        jLabel76 = new javax.swing.JLabel();
        txtuser5 = new javax.swing.JTextField();
        jSeparator25 = new javax.swing.JSeparator();
        comboBoxavion = new javax.swing.JComboBox<>();

        open.setText("jMenuItem1");
        ppMenuTabla.add(open);

        editar.setText("jMenuItem1");
        ppMenuTabla.add(editar);

        eliminar.setText("jMenuItem1");
        ppMenuTabla.add(eliminar);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(55, 54, 86));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel4.setBackground(new java.awt.Color(55, 54, 86));
        jPanel4.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jPanel4MouseMoved(evt);
            }
        });
        jPanel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel4MouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jPanel4MouseExited(evt);
            }
        });
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Inicio");
        jPanel4.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 10, 50, 34));

        jLabel5.setIcon(new javax.swing.ImageIcon("C:\\Users\\Camilo Jurado\\OneDrive\\Desktop\\Resourse\\pagina-de-inicio.png")); // NOI18N
        jPanel4.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, 40, 50));

        jPanel2.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 150, 200, 40));

        jPanel7.setBackground(new java.awt.Color(55, 54, 86));
        jPanel7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel8.setBackground(new java.awt.Color(55, 54, 86));
        jPanel8.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jPanel8MouseMoved(evt);
            }
        });
        jPanel8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jPanel8MouseExited(evt);
            }
        });
        jPanel8.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Inicio");
        jPanel8.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 10, 50, 34));

        jLabel9.setIcon(new javax.swing.ImageIcon("C:\\Users\\Camilo Jurado\\OneDrive\\Desktop\\Resourse\\pagina-de-inicio.png")); // NOI18N
        jPanel8.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, 40, 50));

        jPanel7.add(jPanel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 150, 200, 40));

        jPanel9.setBackground(new java.awt.Color(55, 54, 86));
        jPanel9.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jPanel9MouseMoved(evt);
            }
        });
        jPanel9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel9MouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jPanel9MouseExited(evt);
            }
        });
        jPanel9.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel10.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Aviones");
        jPanel9.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 0, 93, 34));

        jLabel11.setIcon(new javax.swing.ImageIcon("C:\\Users\\Camilo Jurado\\OneDrive\\Desktop\\Resourse\\avion (3).png")); // NOI18N
        jPanel9.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, 40, 40));

        jPanel7.add(jPanel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 200, 200, -1));

        jLabel22.setIcon(new javax.swing.ImageIcon("C:\\Users\\Camilo Jurado\\OneDrive\\Desktop\\Resourse\\hombre-joven-con-corbata.png")); // NOI18N
        jPanel7.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 30, 60, 90));

        jPanel10.setBackground(new java.awt.Color(55, 54, 86));
        jPanel10.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jPanel10MouseMoved(evt);
            }
        });
        jPanel10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel10MouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jPanel10MouseExited(evt);
            }
        });
        jPanel10.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel15.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("Pilotos");
        jPanel10.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 10, 110, 34));

        jLabel21.setIcon(new javax.swing.ImageIcon("C:\\Users\\Camilo Jurado\\OneDrive\\Desktop\\Resourse\\lanza-libre.png")); // NOI18N
        jPanel10.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, -1, 40));

        jPanel7.add(jPanel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 250, 200, -1));

        jButton1.setText("Salir");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel7.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 460, -1, -1));

        jPanel2.add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 200, 510));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 200, 510));

        jPanel3.setBackground(new java.awt.Color(204, 204, 204));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel1.setText("Admin Panel");
        jPanel3.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 20, 179, 33));

        jSeparator1.setForeground(new java.awt.Color(0, 0, 0));
        jPanel3.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, 160, 10));

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 0, 900, 70));

        jPanel6.setBackground(new java.awt.Color(255, 255, 255));
        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Tablepiloto.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Codigo_piloto", "Nombre", "Apellido", "Correo", "Telefono", "Aerolinia"
            }
        ));
        jScrollPane1.setViewportView(Tablepiloto);

        jPanel6.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 40, 760, 290));

        jButton3.setText("Refresh");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel6.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, -1, -1));

        jTabbedPane1.addTab("tab1", jPanel6);

        jPanel11.setBackground(new java.awt.Color(255, 255, 255));
        jPanel11.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel23.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel23.setText("Modelo");
        jPanel11.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 50, 80, 34));

        jTextField5.setBorder(null);
        jPanel11.add(jTextField5, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 50, 450, 30));

        jSeparator8.setForeground(new java.awt.Color(0, 0, 0));
        jPanel11.add(jSeparator8, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 80, 450, 10));

        jLabel24.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel24.setText("Matricula");
        jPanel11.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 100, 100, 34));

        jTextField8.setBorder(null);
        jPanel11.add(jTextField8, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 100, 450, 30));

        jSeparator9.setForeground(new java.awt.Color(0, 0, 0));
        jPanel11.add(jSeparator9, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 130, 450, 10));

        jLabel25.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel25.setText("Nombre Aerolinea");
        jPanel11.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 160, 170, 34));

        jTextField9.setBorder(null);
        jTextField9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField9ActionPerformed(evt);
            }
        });
        jPanel11.add(jTextField9, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 160, 450, 30));

        jSeparator10.setForeground(new java.awt.Color(0, 0, 0));
        jPanel11.add(jSeparator10, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 190, 450, 10));

        jLabel26.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel26.setText("Capacidad de Pasajeros");
        jPanel11.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 240, 210, 34));

        jTextField10.setBorder(null);
        jTextField10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField10ActionPerformed(evt);
            }
        });
        jPanel11.add(jTextField10, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 240, 450, 30));

        jSeparator11.setForeground(new java.awt.Color(0, 0, 0));
        jPanel11.add(jSeparator11, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 270, 450, 10));

        jLabel27.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel27.setForeground(new java.awt.Color(204, 51, 0));
        jLabel27.setText("*");
        jPanel11.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 40, 20, 34));

        jLabel28.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel28.setForeground(new java.awt.Color(204, 51, 0));
        jLabel28.setText("*");
        jPanel11.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 100, 20, 34));

        jLabel29.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel29.setForeground(new java.awt.Color(204, 51, 0));
        jLabel29.setText("*");
        jPanel11.add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 160, 20, 34));

        jLabel30.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel30.setForeground(new java.awt.Color(204, 51, 0));
        jLabel30.setText("*");
        jPanel11.add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 240, 20, 34));

        jSeparator12.setForeground(new java.awt.Color(0, 0, 0));
        jPanel11.add(jSeparator12, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 320, 190, 10));

        jLabel31.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel31.setText("Destino Inicial");
        jPanel11.add(jLabel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 290, 130, 34));

        jComboBox3.setBackground(new java.awt.Color(0, 0, 0, 0));
        jComboBox3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "<Seleccione El Origen>", "Aeropuerto Internacional de la Ciudad de México (MEX)", "Aeropuerto Internacional de Los Ángeles (LAX)", "Aeropuerto Adolfo Suárez Madrid-Barajas (MAD)", "Aeropuerto Internacional de São Paulo/Guarulhos (GRU)", "Aeropuerto Internacional Ministro Pistarini (EZE)", "Aeropuerto Internacional Jorge Chávez (LIM)", "Aeropuerto Internacional de Toronto Pearson (YYZ)", "Aeropuerto de Sídney (SYD)", "Aeropuerto Internacional de Narita (NRT)", "Origen: Aeropuerto Internacional O.R. Tambo (JNB)" }));
        jComboBox3.setBorder(null);
        jPanel11.add(jComboBox3, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 292, 190, 30));

        jLabel32.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel32.setText("Final");
        jPanel11.add(jLabel32, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 290, 50, 34));

        jSeparator14.setForeground(new java.awt.Color(0, 0, 0));
        jPanel11.add(jSeparator14, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 320, 190, 10));

        jComboBox4.setBackground(new java.awt.Color(0, 0, 0, 0));
        jComboBox4.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "<Selecciones el Destino>", "Aeropuerto Internacional de Cancún (CUN)", "Aeropuerto Internacional John F. Kennedy (JFK)", "Aeropuerto de Barcelona-El Prat (BCN)", "Aeropuerto Internacional de Río de Janeiro/Galeão (GIG)", "Aeropuerto Internacional de Mendoza (MDZ)", "Aeropuerto Internacional Alejandro Velasco Astete (CUZ)", "Aeropuerto Internacional de Vancouver (YVR)", "Aeropuerto de Melbourne (MEL)", "Aeropuerto Internacional de Kansai (KIX)", "Aeropuerto Internacional de Ciudad del Cabo (CPT)" }));
        jComboBox4.setBorder(null);
        jPanel11.add(jComboBox4, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 290, 180, 30));

        jSeparator13.setForeground(new java.awt.Color(0, 0, 0));
        jPanel11.add(jSeparator13, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 320, 190, 10));

        jButton2.setText("Agregar");
        jPanel11.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 350, -1, -1));

        jTabbedPane1.addTab("tab2", jPanel11);

        jPanel25.setBackground(new java.awt.Color(255, 255, 255));
        jPanel25.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel25.add(jLabel55, new org.netbeans.lib.awtextra.AbsoluteConstraints(67, 32, -1, -1));
        jPanel25.add(jLabel56, new org.netbeans.lib.awtextra.AbsoluteConstraints(112, 32, -1, -1));
        jPanel25.add(jLabel57, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 32, -1, -1));
        jPanel25.add(jSeparator7, new org.netbeans.lib.awtextra.AbsoluteConstraints(33, 44, 370, 10));
        jPanel25.add(jLabel58, new org.netbeans.lib.awtextra.AbsoluteConstraints(27, 44, -1, 336));
        jPanel25.add(jLabel59, new org.netbeans.lib.awtextra.AbsoluteConstraints(39, 32, -1, -1));

        jLabel60.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel60.setForeground(new java.awt.Color(255, 255, 255));
        jLabel60.setText("Classroom");
        jPanel25.add(jLabel60, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 10, 140, 30));

        jProgressBar7.setBackground(new java.awt.Color(255, 255, 255));
        jProgressBar7.setForeground(new java.awt.Color(0, 204, 204));
        jProgressBar7.setPreferredSize(new java.awt.Dimension(146, 10));
        jProgressBar7.setString("");
        jProgressBar7.setStringPainted(true);
        jPanel25.add(jProgressBar7, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 20, 220, 10));

        jLabel61.setText("Nombre*:");
        jPanel25.add(jLabel61, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 20, 260, 29));

        txtNombre.setBackground(new java.awt.Color(0, 0, 0, 0));
        txtNombre.setBorder(null);
        txtNombre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtNombreKeyPressed(evt);
            }
        });
        jPanel25.add(txtNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 50, 280, 20));

        jSeparator15.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator15.setForeground(new java.awt.Color(0, 0, 0));
        jPanel25.add(jSeparator15, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 130, 280, 10));

        btnContratar.setText("Contratar");
        btnContratar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnContratarActionPerformed(evt);
            }
        });
        jPanel25.add(btnContratar, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 350, 130, -1));

        jLabel62.setText("Apellido:*");
        jPanel25.add(jLabel62, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 80, 230, 29));

        txtApellidos.setBackground(new java.awt.Color(0, 0, 0, 0));
        txtApellidos.setBorder(null);
        txtApellidos.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtApellidosKeyPressed(evt);
            }
        });
        jPanel25.add(txtApellidos, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 110, 280, 20));

        jSeparator16.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator16.setForeground(new java.awt.Color(0, 0, 0));
        jPanel25.add(jSeparator16, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 70, 280, 20));

        jLabel64.setText("Correo:*");
        jPanel25.add(jLabel64, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 140, 230, 29));

        txtCorreo.setBackground(new java.awt.Color(0, 0, 0, 0));
        txtCorreo.setBorder(null);
        txtCorreo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtCorreoKeyPressed(evt);
            }
        });
        jPanel25.add(txtCorreo, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 170, 280, 20));

        jSeparator17.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator17.setForeground(new java.awt.Color(0, 0, 0));
        jPanel25.add(jSeparator17, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 190, 280, 10));

        jSeparator19.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator19.setForeground(new java.awt.Color(0, 0, 0));
        jPanel25.add(jSeparator19, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 250, 280, 10));

        jPanel26.setBackground(new java.awt.Color(255, 255, 255));
        jPanel26.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel26.add(jLabel63, new org.netbeans.lib.awtextra.AbsoluteConstraints(67, 32, -1, -1));
        jPanel26.add(jLabel67, new org.netbeans.lib.awtextra.AbsoluteConstraints(112, 32, -1, -1));
        jPanel26.add(jLabel68, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 32, -1, -1));
        jPanel26.add(jSeparator20, new org.netbeans.lib.awtextra.AbsoluteConstraints(33, 44, 370, 10));
        jPanel26.add(jLabel69, new org.netbeans.lib.awtextra.AbsoluteConstraints(27, 44, -1, 336));
        jPanel26.add(jLabel70, new org.netbeans.lib.awtextra.AbsoluteConstraints(39, 32, -1, -1));

        jLabel71.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel71.setForeground(new java.awt.Color(255, 255, 255));
        jLabel71.setText("Classroom");
        jPanel26.add(jLabel71, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 10, 140, 30));

        jProgressBar8.setBackground(new java.awt.Color(255, 255, 255));
        jProgressBar8.setForeground(new java.awt.Color(0, 204, 204));
        jProgressBar8.setPreferredSize(new java.awt.Dimension(146, 10));
        jProgressBar8.setString("");
        jProgressBar8.setStringPainted(true);
        jPanel26.add(jProgressBar8, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 20, 220, 10));

        jLabel72.setText("Nombre*:");
        jPanel26.add(jLabel72, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 20, 260, 29));

        txtNombre1.setBackground(new java.awt.Color(0, 0, 0, 0));
        txtNombre1.setBorder(null);
        txtNombre1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtNombre1KeyPressed(evt);
            }
        });
        jPanel26.add(txtNombre1, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 50, 280, 20));

        jSeparator21.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator21.setForeground(new java.awt.Color(0, 0, 0));
        jPanel26.add(jSeparator21, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 130, 280, 10));

        btnContratar1.setText("Contratar");
        btnContratar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnContratar1ActionPerformed(evt);
            }
        });
        jPanel26.add(btnContratar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 350, 130, -1));

        jLabel73.setText("Apellido:*");
        jPanel26.add(jLabel73, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 80, 230, 29));

        txtApellidos1.setBackground(new java.awt.Color(0, 0, 0, 0));
        txtApellidos1.setBorder(null);
        txtApellidos1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtApellidos1KeyPressed(evt);
            }
        });
        jPanel26.add(txtApellidos1, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 110, 280, 20));

        jSeparator22.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator22.setForeground(new java.awt.Color(0, 0, 0));
        jPanel26.add(jSeparator22, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 70, 280, 20));

        jLabel74.setText("Correo:*");
        jPanel26.add(jLabel74, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 140, 230, 29));

        txtCorreo1.setBackground(new java.awt.Color(0, 0, 0, 0));
        txtCorreo1.setBorder(null);
        txtCorreo1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtCorreo1KeyPressed(evt);
            }
        });
        jPanel26.add(txtCorreo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 170, 280, 20));

        jSeparator23.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator23.setForeground(new java.awt.Color(0, 0, 0));
        jPanel26.add(jSeparator23, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 190, 280, 10));

        jLabel75.setText("Telefono:*");
        jPanel26.add(jLabel75, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 200, 230, 29));

        txtTelefono.setBackground(new java.awt.Color(0, 0, 0, 0));
        txtTelefono.setBorder(null);
        txtTelefono.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTelefonoActionPerformed(evt);
            }
        });
        jPanel26.add(txtTelefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 230, 280, 20));

        txtTelefono1.setBackground(new java.awt.Color(0, 0, 0, 0));
        txtTelefono1.setBorder(null);
        txtTelefono1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtTelefono1KeyPressed(evt);
            }
        });
        jPanel26.add(txtTelefono1, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 230, 280, 20));

        jSeparator24.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator24.setForeground(new java.awt.Color(0, 0, 0));
        jPanel26.add(jSeparator24, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 250, 280, 10));

        jLabel76.setForeground(new java.awt.Color(255, 255, 255));
        jLabel76.setText("Telefono:*");
        jPanel26.add(jLabel76, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 200, 230, 29));

        txtuser5.setBackground(new java.awt.Color(0, 0, 0, 0));
        txtuser5.setForeground(new java.awt.Color(255, 255, 255));
        txtuser5.setBorder(null);
        txtuser5.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtuser5KeyPressed(evt);
            }
        });
        jPanel26.add(txtuser5, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 230, 280, 20));

        jSeparator25.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator25.setForeground(new java.awt.Color(0, 0, 0));
        jPanel26.add(jSeparator25, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 250, 280, 10));

        comboBoxavion.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Brazil", "Argentina", "Estados Unidos", "Canada", "Mexico" }));
        comboBoxavion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboBoxavionActionPerformed(evt);
            }
        });
        jPanel26.add(comboBoxavion, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 280, 110, 30));

        jPanel25.add(jPanel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jTabbedPane1.addTab("tab3", jPanel25);

        jPanel1.add(jTabbedPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 30, 900, 480));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jPanel4MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel4MouseMoved
        jPanel4.setBackground(new Color(235,106,2));
    }//GEN-LAST:event_jPanel4MouseMoved

    private void jPanel4MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel4MouseExited
        jPanel4.setBackground(new Color(55,54,86));
    }//GEN-LAST:event_jPanel4MouseExited

    private void jPanel8MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel8MouseMoved
        // TODO add your handling code here:
    }//GEN-LAST:event_jPanel8MouseMoved

    private void jPanel8MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel8MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_jPanel8MouseExited

    private void jPanel9MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel9MouseMoved
        jPanel9.setBackground(new Color(235,106,2));
    }//GEN-LAST:event_jPanel9MouseMoved

    private void jPanel9MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel9MouseExited
        jPanel9.setBackground(new Color(55,54,86));
    }//GEN-LAST:event_jPanel9MouseExited

    private void jPanel10MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel10MouseMoved
        jPanel10.setBackground(new Color(235,106,2));
    }//GEN-LAST:event_jPanel10MouseMoved

    private void jPanel10MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel10MouseExited
        jPanel10.setBackground(new Color(55,54,86));
    }//GEN-LAST:event_jPanel10MouseExited

    private void jTextField9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField9ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField9ActionPerformed

    private void jTextField10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField10ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField10ActionPerformed

    private void jPanel4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel4MouseClicked
        jTabbedPane1.setSelectedIndex(0);
    }//GEN-LAST:event_jPanel4MouseClicked

    private void jPanel9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel9MouseClicked
        jTabbedPane1.setSelectedIndex(1);
    }//GEN-LAST:event_jPanel9MouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        new Inicio().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jPanel10MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel10MouseClicked
        jTabbedPane1.setSelectedIndex(2);
    }//GEN-LAST:event_jPanel10MouseClicked

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        cargarPilotoEnTabla();
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void comboBoxavionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboBoxavionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboBoxavionActionPerformed

    private void txtuser5KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtuser5KeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtuser5KeyPressed

    private void txtTelefono1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTelefono1KeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTelefono1KeyPressed

    private void txtTelefonoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTelefonoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTelefonoActionPerformed

    private void txtCorreo1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCorreo1KeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCorreo1KeyPressed

    private void txtApellidos1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtApellidos1KeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtApellidos1KeyPressed

    private void btnContratar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnContratar1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnContratar1ActionPerformed

    private void txtNombre1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNombre1KeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombre1KeyPressed

    private void txtCorreoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCorreoKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCorreoKeyPressed

    private void txtApellidosKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtApellidosKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtApellidosKeyPressed

    private void btnContratarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnContratarActionPerformed
        
        String nombre = txtNombre.getText();
        String apellidos = txtApellidos.getText();
        String correo = txtCorreo.getText();
        String telefono = txtTelefono.getText();
        String avion = (String) comboBoxavion.getSelectedItem();


        if (nombre.isEmpty() || apellidos.isEmpty() || correo.isEmpty() || telefono.isEmpty() || avion == null) {
            JOptionPane.showMessageDialog(this, "Por favor, complete todos los campos.", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        try {
            PilotoDAO pilotoDAO = new PilotoDAO();

            LocalDate fechaContratacion = LocalDate.now();

            pilotoDAO.contratarPiloto(nombre, apellidos, correo, telefono, fechaContratacion, avion);

            JOptionPane.showMessageDialog(this, "Piloto contratado exitosamente", "Exito", JOptionPane.INFORMATION_MESSAGE);

            limpiarCampos();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error al contratar al profesor: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnContratarActionPerformed

    private void txtNombreKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNombreKeyPressed
        if (evt.getKeyCode() == evt.getKeyCode()) {
            txtNombre.requestFocus();
        }
    }//GEN-LAST:event_txtNombreKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Administrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Administrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Administrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Administrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Administrador().setVisible(true);
            }
        });
    }
    private void limpiarCampos() {
        txtNombre.setText("");
        txtApellidos.setText("");
        txtCorreo.setText("");
        txtTelefono.setText("");
        comboBoxavion.setSelectedIndex(0);
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable Tablepiloto;
    private javax.swing.JButton btnContratar;
    private javax.swing.JButton btnContratar1;
    private javax.swing.JComboBox<String> comboBoxavion;
    private javax.swing.JMenuItem editar;
    private javax.swing.JMenuItem eliminar;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JComboBox<String> jComboBox3;
    private javax.swing.JComboBox<String> jComboBox4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel55;
    private javax.swing.JLabel jLabel56;
    private javax.swing.JLabel jLabel57;
    private javax.swing.JLabel jLabel58;
    private javax.swing.JLabel jLabel59;
    private javax.swing.JLabel jLabel60;
    private javax.swing.JLabel jLabel61;
    private javax.swing.JLabel jLabel62;
    private javax.swing.JLabel jLabel63;
    private javax.swing.JLabel jLabel64;
    private javax.swing.JLabel jLabel67;
    private javax.swing.JLabel jLabel68;
    private javax.swing.JLabel jLabel69;
    private javax.swing.JLabel jLabel70;
    private javax.swing.JLabel jLabel71;
    private javax.swing.JLabel jLabel72;
    private javax.swing.JLabel jLabel73;
    private javax.swing.JLabel jLabel74;
    private javax.swing.JLabel jLabel75;
    private javax.swing.JLabel jLabel76;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel25;
    private javax.swing.JPanel jPanel26;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JProgressBar jProgressBar7;
    private javax.swing.JProgressBar jProgressBar8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator10;
    private javax.swing.JSeparator jSeparator11;
    private javax.swing.JSeparator jSeparator12;
    private javax.swing.JSeparator jSeparator13;
    private javax.swing.JSeparator jSeparator14;
    private javax.swing.JSeparator jSeparator15;
    private javax.swing.JSeparator jSeparator16;
    private javax.swing.JSeparator jSeparator17;
    private javax.swing.JSeparator jSeparator19;
    private javax.swing.JSeparator jSeparator20;
    private javax.swing.JSeparator jSeparator21;
    private javax.swing.JSeparator jSeparator22;
    private javax.swing.JSeparator jSeparator23;
    private javax.swing.JSeparator jSeparator24;
    private javax.swing.JSeparator jSeparator25;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JSeparator jSeparator8;
    private javax.swing.JSeparator jSeparator9;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextField jTextField10;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JTextField jTextField9;
    private javax.swing.JMenuItem open;
    private javax.swing.JPopupMenu ppMenuTabla;
    private javax.swing.JTextField txtApellidos;
    private javax.swing.JTextField txtApellidos1;
    private javax.swing.JTextField txtCorreo;
    private javax.swing.JTextField txtCorreo1;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtNombre1;
    private javax.swing.JTextField txtTelefono;
    private javax.swing.JTextField txtTelefono1;
    private javax.swing.JTextField txtuser5;
    // End of variables declaration//GEN-END:variables


}
